# Generated by Django 3.2.6 on 2021-08-10 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0002_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='away_token',
            field=models.DecimalField(decimal_places=4, default=100.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='home_token',
            field=models.DecimalField(decimal_places=4, default=100.0, max_digits=20),
        ),
        migrations.CreateModel(
            name='User_Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_token', models.DecimalField(decimal_places=4, default=50.0, max_digits=20)),
                ('away_token', models.DecimalField(decimal_places=4, default=50.0, max_digits=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_user', to='market.teamgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
