# Generated by Django 3.2.6 on 2021-09-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210810_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='market_conf',
            field=models.JSONField(default={}),
        ),
    ]
