# Generated by Django 3.2.6 on 2021-09-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_teamgame_market_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='contract_abi',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='contract_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='teamgame',
            name='market_conf',
            field=models.JSONField(default={'null': 'null'}),
        ),
    ]
