# Generated by Django 3.2.6 on 2021-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20210903_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgame',
            name='contract_abi',
            field=models.TextField(default=''),
        ),
    ]
