# Generated by Django 3.2.6 on 2021-09-08 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_teamgame_contract_abi'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
