# Generated by Django 3.2.6 on 2021-09-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20210908_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='winner',
            field=models.CharField(choices=[('home', 'home'), ('away', 'away')], default='home', max_length=4),
        ),
        migrations.AddField(
            model_name='user_market',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
