# Generated by Django 3.2.6 on 2021-09-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20210909_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='condition_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teamgame',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teamgame',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
