# Generated by Django 3.2.6 on 2021-09-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20210909_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgame',
            name='condition_id',
            field=models.TextField(default='need activating'),
        ),
        migrations.AlterField(
            model_name='teamgame',
            name='contract_abi',
            field=models.TextField(default='need activating'),
        ),
        migrations.AlterField(
            model_name='teamgame',
            name='contract_address',
            field=models.CharField(default='need activating', max_length=200),
        ),
        migrations.AlterField(
            model_name='teamgame',
            name='positionIdHi',
            field=models.TextField(default='need activating'),
        ),
        migrations.AlterField(
            model_name='teamgame',
            name='positionIdLo',
            field=models.TextField(default='need activating'),
        ),
    ]
