# Generated by Django 3.2.6 on 2021-09-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20210910_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgame',
            name='game_end',
            field=models.BooleanField(default=False),
        ),
    ]
