# Generated by Django 3.2.6 on 2021-09-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_teamgame_game_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_market',
            name='before_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_market',
            name='before_sell',
            field=models.BooleanField(default=False),
        ),
    ]
