# Generated by Django 3.2.6 on 2021-09-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20210915_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='market_price',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='tx_receipt',
            field=models.TextField(default='receipt of transaction'),
        ),
    ]
