# Generated by Django 3.2.6 on 2021-09-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20210928_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
