# Generated by Django 3.2.6 on 2021-11-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_auto_20211115_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgame',
            name='game_close_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
