# Generated by Django 3.2.6 on 2021-11-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_teamgame_game_close_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgame',
            name='game_close_time',
            field=models.DateTimeField(),
        ),
    ]
